"""compile_derive — two-phase derivation via fold_schema.

    from emergent.wire.derive import compile_derive

    @schema_meta(CRUD("/users", Users), Paginated(20))
    @dataclass
    class User:
        id: Annotated[int, Identity]
        name: str

    ctx = compile_derive(User)
    endpoint = materialize(ctx)
"""

from __future__ import annotations

from emergent.wire.compile._core import fold_schema
from emergent.wire.derive._ctx import DeriveCtx
from emergent.wire.derive._protocols import (
    DeriveAugmentable,
    DeriveGeneratable,
    DeriveModifiable,
)


def _validate_specs[EntityT](ctx: DeriveCtx[EntityT]) -> None:
    """Check for duplicate spec names after Phase 1. Raises ValueError on conflict."""
    seen: dict[tuple[str, str], str] = {}
    for spec in ctx.specs:
        key = (spec.entity_name, spec.name)
        if key in seen:
            raise ValueError(
                f"Conflict: spec '{spec.name}' for '{spec.entity_name}' "
                f"generated by both '{seen[key]}' and '{spec.source}'"
            )
        seen[key] = spec.source


def compile_derive[EntityT](cls: type[EntityT]) -> DeriveCtx[EntityT]:
    """Three-phase derive compilation via fold_schema.

    Phase 1: fold DeriveGeneratable caps — CRUD generates OpSpecs
    Validation: check for duplicate spec names
    Phase 2: fold DeriveModifiable caps — Paginated/SoftDelete transform specs
    Phase 3: fold DeriveAugmentable caps — post-modification augmentation

    Uses wire's fold_schema() which folds get_schema_meta(cls) capabilities.
    No new fold mechanism — same fold, same isinstance dispatch, same open-world.

    Returns DeriveCtx with accumulated specs, operations, and capabilities.
    When no derive capabilities are present, returns empty DeriveCtx (no-op).
    """
    try:
        ctx: DeriveCtx[EntityT] = DeriveCtx.from_entity(cls)
    except TypeError:
        # Not a structured type (dataclass/Pydantic/TypedDict/NamedTuple)
        ctx = DeriveCtx.from_subject(cls)
    ctx = fold_schema(cls, ctx, DeriveGeneratable, "compile_derive_generate")
    _validate_specs(ctx)
    ctx = fold_schema(cls, ctx, DeriveModifiable, "compile_derive_modify")
    ctx = fold_schema(cls, ctx, DeriveAugmentable, "compile_derive_augment")
    return ctx


__all__ = ("compile_derive",)
