"""compile_derive — three-phase derivation via fold_schema.

    from emergent.wire.derive import compile_derive, materialize

    @schema_meta(CRUD("/users", Users), Paginated(20))
    @dataclass
    class User:
        id: Annotated[int, Identity]
        name: str

    ctxs = compile_derive(User)
    endpoints = [materialize(ctx) for ctx in ctxs]

Multiple generators (e.g. http_crud + cli_crud) are compiled independently.
Capabilities are **positional** — a modifier binds to its preceding generator:

    @schema_meta(
        Paginated(20),                              # global — before any generator
        http_crud("/users", Store),                  # generator 0
        ProjectResponse(exclude=("secret",)),        # local to generator 0
        http_crud("/users/me", Store, ops=(GET,)),   # generator 1
        Authenticated(BearerExtract(), validate),    # local to generator 1
    )
    @dataclass
    class User: ...

    ctxs = compile_derive(User)  # [public_ctx, authed_ctx]
"""

from __future__ import annotations

from emergent.wire.axis.schema._universal import get_schema_meta
from emergent.wire.compile._core import fold, fold_schema
from emergent.wire.derive._ctx import DeriveCtx
from emergent.wire.derive._protocols import (
    DeriveAugmentable,
    DeriveGeneratable,
    DeriveModifiable,
)


def _validate_specs[EntityT](ctx: DeriveCtx[EntityT]) -> None:
    """Check for duplicate spec names after a generate phase."""
    seen: dict[tuple[str, str], str] = {}
    for spec in ctx.specs:
        key = (spec.entity_name, spec.name)
        if key in seen:
            raise ValueError(
                f"Conflict: spec '{spec.name}' for '{spec.entity_name}' "
                f"generated by both '{seen[key]}' and '{spec.source}'"
            )
        seen[key] = spec.source


def _make_ctx[EntityT](cls: type[EntityT]) -> DeriveCtx[EntityT]:
    """Create initial DeriveCtx from entity or plain class."""
    try:
        return DeriveCtx.from_entity(cls)
    except TypeError:
        return DeriveCtx.from_subject(cls)


def compile_derive[EntityT](cls: type[EntityT]) -> list[DeriveCtx[EntityT]]:
    """Three-phase derive compilation.

    Phase 1: DeriveGeneratable — CRUD generates OpSpecs
    Phase 2: DeriveModifiable  — Paginated/SoftDelete transform specs
    Phase 3: DeriveAugmentable — post-modification augmentation

    Capabilities in @schema_meta are **positional**:
    - Caps before the first generator are **global** (apply to all generators)
    - Caps after a generator are **local** (apply to that generator only)

    Returns list[DeriveCtx] — one per generator group.
    Single generator → single-element list. Zero generators → single empty ctx.
    """
    caps = get_schema_meta(cls)

    generators: list[DeriveGeneratable] = []
    for cap in caps:
        if isinstance(cap, DeriveGeneratable):
            generators.append(cap)

    if len(generators) <= 1:
        # 0-1 generators — single fold, standard path (all caps apply)
        ctx: DeriveCtx[EntityT] = _make_ctx(cls)
        ctx = fold_schema(cls, ctx, DeriveGeneratable, "compile_derive_generate")
        _validate_specs(ctx)
        ctx = fold_schema(cls, ctx, DeriveModifiable, "compile_derive_modify")
        ctx = fold_schema(cls, ctx, DeriveAugmentable, "compile_derive_augment")
        return [ctx]

    # Multiple generators — positional: modifiers bind to preceding generator
    global_caps: list[object] = []
    groups: list[tuple[DeriveGeneratable, list[object]]] = []
    current_gen: DeriveGeneratable | None = None
    current_local: list[object] = []

    for cap in caps:
        if isinstance(cap, DeriveGeneratable):
            if current_gen is not None:
                groups.append((current_gen, current_local))
            current_gen = cap
            current_local = []
        else:
            if current_gen is None:
                global_caps.append(cap)
            else:
                current_local.append(cap)

    if current_gen is not None:
        groups.append((current_gen, current_local))

    results: list[DeriveCtx[EntityT]] = []
    for gen, local_caps in groups:
        ctx = _make_ctx(cls)

        # Phase 1: generate — only this generator
        ctx = gen.compile_derive_generate(ctx)
        _validate_specs(ctx)

        # Phase 2+3: modify & augment — generator + global caps + local caps
        group: list[object] = [gen, *global_caps, *local_caps]
        ctx = fold(group, ctx, DeriveModifiable, "compile_derive_modify")
        ctx = fold(group, ctx, DeriveAugmentable, "compile_derive_augment")

        results.append(ctx)

    return results


__all__ = ("compile_derive",)
