"""DerivedMetadata — metadata that survives materialize().

Attached to each Exposure as a SurfaceCapability so target compilers
can inspect derivation origin without needing DeriveCtx.

    from emergent.wire.derive._metadata import DerivedMetadata
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING

from emergent.wire.axis.surface.capabilities import SurfaceCapability

if TYPE_CHECKING:
    from emergent.wire.derive._effects import DerivationEffect


@dataclass(frozen=True, slots=True)
class DerivedMetadata(SurfaceCapability):
    """Derivation metadata preserved through materialize().

    Target compilers can inspect:
    - Is this a Read or Mutation?
    - Was this generated by CRUD or hand-crafted?
    - What are the identity fields?
    - Which handler template was used?
    """

    entity: type
    entity_name: str
    spec_name: str
    source: str
    effects: tuple[DerivationEffect, ...]
    identity_fields: tuple[str, ...]
    handler_template_type: str


__all__ = ("DerivedMetadata",)
